# syntax=docker/dockerfile:1

FROM python:3.12-slim
WORKDIR /app

RUN pip install --no-cache-dir uv

COPY requirements.txt ./
RUN uv pip install --system --no-cache -r requirements.txt

COPY . .

ENV PORT=<%= it.port %>
EXPOSE <%= it.port %>

CMD ["python", "server.py"]
